version: '3.6'
services:
  mysql:
    image: mysql:5.7.37
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=schoolregistration
      - MYSQL_ROOT_PASSWORD=schoolregistration
      - MYSQL_USER=schoolregistration
      - MYSQL_PASSWORD=schoolregistration
    command: 
     - --table_definition_cache=100
     - --performance_schema=0
     - --default-authentication-plugin=mysql_native_password
     - --innodb_use_native_aio=0
    volumes: 
        - ./etc/init.sql:/docker-entrypoint-initdb.d/init-script.sql
        - ./dbdata:/var/lib/mysql
    container_name: mysqldb
  schoolregistration:
    image: schoolregistration:0.0.1-SNAPSHOT
    ports:
      - 9090:9090
    environment:
      - MYSQL_HOST=mysql
    depends_on:
      - mysql
